# Generated by Django 4.0.6 on 2022-10-04 09:00

import account.models
import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='mb_seq', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='mb_id', max_length=200, unique=True)),
                ('password', models.CharField(db_column='mb_password', max_length=200)),
                ('mbm_seq', models.PositiveIntegerField(null=True)),
                ('ctl_seq1', models.PositiveIntegerField(null=True)),
                ('ctl_seq2', models.PositiveIntegerField(null=True)),
                ('ctl_seq3', models.PositiveIntegerField(null=True)),
                ('ctl_seq4', models.PositiveIntegerField(null=True)),
                ('mb_name', models.CharField(max_length=100)),
                ('mb_type', models.CharField(max_length=1)),
                ('mb_status', models.CharField(max_length=1)),
                ('mb_profile', models.ImageField(default='avater.jpg', upload_to=account.models.upload_to)),
                ('mb_profile_org', models.CharField(max_length=300)),
                ('mb_email', models.CharField(max_length=200)),
                ('mb_phone', models.CharField(max_length=100)),
                ('mb_active', models.CharField(max_length=1)),
                ('mb_position_seq', models.PositiveIntegerField(null=True)),
                ('mb_position', models.CharField(max_length=200)),
                ('mb_fcm', models.CharField(max_length=200)),
                ('mb_del_date', models.DateTimeField(null=True)),
                ('mb_regdate', models.DateTimeField(default=datetime.datetime.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'member2_tb',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
