# Generated by Django 4.0.6 on 2022-10-04 06:14

import account.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mb_seq', models.AutoField(primary_key=True, serialize=False)),
                ('mbm_seq', models.PositiveIntegerField(null=True)),
                ('ctl_seq1', models.PositiveIntegerField(null=True)),
                ('ctl_seq2', models.PositiveIntegerField(null=True)),
                ('ctl_seq3', models.PositiveIntegerField(null=True)),
                ('ctl_seq4', models.PositiveIntegerField(null=True)),
                ('mb_id', models.CharField(max_length=200, unique=True)),
                ('mb_name', models.CharField(max_length=100)),
                ('mb_password', models.CharField(max_length=200)),
                ('mb_type', models.CharField(max_length=1)),
                ('mb_status', models.CharField(max_length=1)),
                ('mb_profile', models.ImageField(default='avater.jpg', upload_to=account.models.upload_to)),
                ('mb_profile_org', models.CharField(max_length=300)),
                ('mb_email', models.CharField(max_length=200)),
                ('mb_phone', models.CharField(max_length=100)),
                ('mb_active', models.CharField(max_length=1)),
                ('mb_position_seq', models.PositiveIntegerField(null=True)),
                ('mb_position', models.CharField(max_length=200)),
                ('mb_fcm', models.CharField(max_length=200)),
                ('mb_del_date', models.DateTimeField(null=True)),
                ('mb_regdate', models.DateTimeField(default=datetime.datetime.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'member_tb',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('place', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_user_point',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserHomecare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[(1, '일반회원'), (2, '셀러회원')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_user_homecare',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserApt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('R', '일반회원'), ('S', '경비회원'), ('M', '관리소'), ('G', '게스트')], max_length=10)),
                ('apt_key', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_user_apt',
                'managed': True,
            },
        ),
    ]
