# Generated by Django 4.1.3 on 2022-11-11 06:21

import account.models
import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='mb_seq', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='mb_id', max_length=200, unique=True)),
                ('password', models.CharField(db_column='mb_password', max_length=200)),
                ('email', models.CharField(db_column='mb_email', max_length=200)),
                ('mbm_seq', models.PositiveIntegerField(null=True)),
                ('ctl_seq1', models.PositiveIntegerField(null=True)),
                ('ctl_seq2', models.PositiveIntegerField(null=True)),
                ('ctl_seq3', models.PositiveIntegerField(null=True)),
                ('ctl_seq4', models.PositiveIntegerField(null=True)),
                ('point', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mb_name', models.CharField(max_length=100)),
                ('mb_type', models.CharField(max_length=1)),
                ('mb_status', models.CharField(max_length=1)),
                ('mb_profile', models.ImageField(default='avater.jpg', upload_to=account.models.upload_to)),
                ('mb_profile_org', models.CharField(max_length=300)),
                ('mb_phone', models.CharField(max_length=100)),
                ('mb_active', models.CharField(max_length=1)),
                ('mb_position_seq', models.PositiveIntegerField(null=True)),
                ('mb_position', models.CharField(max_length=200)),
                ('mb_fcm', models.CharField(max_length=200)),
                ('mb_del_date', models.DateTimeField(null=True)),
                ('mb_regdate', models.DateTimeField(default=datetime.datetime.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'member_tb',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('base_address', models.CharField(max_length=255)),
                ('detail_address', models.CharField(max_length=255)),
                ('zipcode', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member_shipping_address_tb',
            },
        ),
    ]
