# Generated by Django 4.0.6 on 2022-10-04 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhomecare',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpoint',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserApt',
        ),
        migrations.DeleteModel(
            name='UserHomecare',
        ),
        migrations.DeleteModel(
            name='UserPoint',
        ),
    ]
