# Generated by Django 4.0.6 on 2022-10-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='member_tb',
        ),
    ]
