# Generated by Django 4.1.3 on 2022-11-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='point',
        ),
    ]
