# Generated by Django 4.0.6 on 2022-10-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userhomecare_user_remove_userpoint_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
