# Generated by Django 4.0.6 on 2022-10-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mb_email',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_column='mb_email', max_length=200),
        ),
    ]
