# Generated by Django 4.1.3 on 2022-12-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_user_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mbm_residence_type",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
