# Generated by Django 4.0.6 on 2022-10-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_mb_email_user_email_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
