# Generated by Django 4.0.6 on 2022-10-06 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('base_address', models.CharField(max_length=255)),
                ('detail_address', models.CharField(max_length=255)),
                ('zipcode', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member_shipping_address_tb',
            },
        ),
    ]
