# Generated by Django 4.1.3 on 2022-12-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_user_mbm_residence_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mbm_residence_type",
            field=models.CharField(
                choices=[("1", "LANDLORD"), ("2", "TENANT")], max_length=200
            ),
        ),
    ]
