# Generated by Django 4.1.3 on 2023-09-11 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_user_mbm_residence_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="mbm_residence_type",
        ),
        migrations.CreateModel(
            name="UserSeller",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("bank", models.CharField(default=None, max_length=255, null=True)),
                (
                    "bank_account",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "bank_holder",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "member_seller_tb",
            },
        ),
    ]
