# Generated by Django 4.0.6 on 2022-10-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_usersellerarea'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersellerarea',
            table='ecommerce_user_seller_area',
        ),
    ]
