# Generated by Django 4.0.6 on 2022-10-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_area_productarea'),
        ('account', '0007_alter_usersellerarea_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSellerArea',
        ),
    ]
