# Generated by Django 4.1.3 on 2022-11-10 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_userseller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSeller',
        ),
    ]
