# Generated by Django 4.1.3 on 2023-06-27 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0015_productreviewimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscribeBillingKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billing_key", models.CharField(max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ecommerce_subcribe_billing_key",
            },
        ),
        migrations.CreateModel(
            name="SubscribeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_subscribe", models.BooleanField(default=False)),
                ("subscribed_at", models.DateTimeField()),
                ("product_name", models.CharField(max_length=255)),
                ("product_price", models.PositiveIntegerField()),
                ("variant", models.CharField(max_length=255, null=True)),
                ("variant_value", models.CharField(max_length=255, null=True)),
                ("variant_price", models.PositiveIntegerField(null=True)),
                ("ordered_quantity", models.PositiveIntegerField()),
                ("shipped_quantity", models.PositiveIntegerField(default=0)),
                (
                    "billing_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscribe.subscribebillingkey",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "db_table": "ecommerce_subcribe_item",
            },
        ),
    ]
