# Generated by Django 4.1.3 on 2023-06-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribebillingkey",
            name="billing_key",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="subscribebillingkey",
            table="ecommerce_subscribe_billing_key",
        ),
    ]
