[tool.poetry]
name = "utoville-ecommerce"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "utoville_ecommerce"}]

[tool.poetry.dependencies]
<<<<<<< Updated upstream
python = "^3.10"
Django = "4.0.7"
djangorestframework = "^3.14.0"
django-oauth-toolkit = "^2.1.0"
PyMySQL = "^1.0.2"
Pillow = "^9.2.0"
django-imagekit = "^4.1.0"
django-mathfilters = "^1.0.0"
=======
python = "^3.11"
django = "^4.1.3"
pymysql = "^1.0.2"
django-mathfilters = "^1.0.0"
pillow = "^9.3.0"
django-imagekit = "^4.1.0"
>>>>>>> Stashed changes


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
