# Generated by Django 4.1.3 on 2022-11-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitdone',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Profit',
        ),
        migrations.DeleteModel(
            name='ProfitDone',
        ),
    ]
