# Generated by Django 4.1.3 on 2022-11-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0004_rename_is_done_profit_is_odone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profit',
            name='is_odone',
        ),
    ]
