# Generated by Django 4.1.3 on 2022-11-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0005_remove_profit_is_odone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
