# Generated by Django 4.1.3 on 2022-11-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0006_profit_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='payment_fee',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
