# Generated by Django 4.1.3 on 2022-11-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0008_rename_paid_amount_profit_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profit',
            old_name='amount',
            new_name='profit_amount',
        ),
        migrations.RenameField(
            model_name='profitdone',
            old_name='paid_amount',
            new_name='profit_done_amount',
        ),
    ]
