# Generated by Django 4.1.3 on 2022-11-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0009_rename_amount_profit_profit_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profitdone',
            old_name='profit_done_amount',
            new_name='sum_profit_amount',
        ),
        migrations.RemoveField(
            model_name='profitdone',
            name='payment_fee',
        ),
        migrations.AddField(
            model_name='profit',
            name='charge_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profitdone',
            name='total_payment_fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profitdone',
            name='total_profit_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profit',
            name='payment_fee',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
