# Generated by Django 4.1.3 on 2022-11-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0011_rename_sum_profit_amount_profitdone_profit_done_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profitdone',
            old_name='shipping_fee',
            new_name='total_shipping_fee',
        ),
    ]
