# Generated by Django 4.1.3 on 2022-12-26 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0016_alter_order_txnid"),
        ("profit", "0012_rename_shipping_fee_profitdone_total_shipping_fee"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfitDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("charge_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("charge_fee", models.DecimalField(decimal_places=2, max_digits=14)),
                ("shipping_fee", models.DecimalField(decimal_places=2, max_digits=14)),
                ("profit_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.orderitem",
                    ),
                ),
            ],
            options={
                "db_table": "ecommerce_profit_detail",
            },
        ),
        migrations.RenameField(
            model_name="profit",
            old_name="charge_amount",
            new_name="total_charge_amount",
        ),
        migrations.RenameField(
            model_name="profit",
            old_name="payment_fee",
            new_name="total_charge_fee",
        ),
        migrations.RenameField(
            model_name="profit",
            old_name="profit_amount",
            new_name="total_profit_amount",
        ),
        migrations.RemoveField(
            model_name="profit",
            name="order_item",
        ),
        migrations.RemoveField(
            model_name="profit",
            name="profit_done",
        ),
        migrations.AddField(
            model_name="profit",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profit",
            name="memo",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profit",
            name="status",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profit",
            name="total_shipping_fee",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ProfitDone",
        ),
        migrations.AddField(
            model_name="profitdetail",
            name="profit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profit.profit"
            ),
        ),
    ]
