# Generated by Django 4.1.3 on 2022-12-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profit", "0013_profitdetail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profit",
            name="memo",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profit",
            name="status",
            field=models.CharField(default="정산대기", max_length=255),
        ),
        migrations.AlterField(
            model_name="profit",
            name="total_charge_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="profit",
            name="total_charge_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="profit",
            name="total_profit_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="profit",
            name="total_shipping_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
