# Generated by Django 4.1.3 on 2023-06-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profit", "0014_alter_profit_memo_alter_profit_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profit",
            name="status",
            field=models.CharField(
                choices=[("D", "Done"), ("W", "Wait"), ("H", "Hold")],
                default="W",
                max_length=255,
            ),
        ),
    ]
