# Generated by Django 4.1.3 on 2023-09-11 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profit", "0015_alter_profit_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profit",
            old_name="total_charge_amount",
            new_name="total_paid_amount",
        ),
        migrations.RenameField(
            model_name="profit",
            old_name="total_charge_fee",
            new_name="total_payment_fee",
        ),
        migrations.RenameField(
            model_name="profitdetail",
            old_name="charge_amount",
            new_name="paid_amount",
        ),
        migrations.RenameField(
            model_name="profitdetail",
            old_name="charge_fee",
            new_name="payment_fee",
        ),
    ]
