# Generated by Django 4.0.6 on 2022-10-05 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productimg_user_productimg_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImg',
            new_name='ProductImage',
        ),
        migrations.AddField(
            model_name='product',
            name='option_json',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
