# Generated by Django 4.0.6 on 2022-10-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_productimg_productimage_product_option_json_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimage',
            table='ecommerce_product_image',
        ),
    ]
