# Generated by Django 4.1.3 on 2022-11-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productvariantvalue_price_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantvalue',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
    ]
