# Generated by Django 4.0.6 on 2022-10-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productimage_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='img',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
