# Generated by Django 4.0.6 on 2022-10-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_usersellerarea'),
        ('product', '0005_rename_category_product_category_third_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='area',
            field=models.ManyToManyField(to='account.usersellerarea'),
        ),
    ]
