# Generated by Django 4.1.3 on 2022-11-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productvariantvalue_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_deleted',
        ),
    ]
