# Generated by Django 4.0.6 on 2022-10-07 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='area',
        ),
        migrations.CreateModel(
            name='ProductArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'ecommerce_product_area',
            },
        ),
    ]
