# Generated by Django 4.0.6 on 2022-10-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_content_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='option_json',
        ),
    ]
