# Generated by Django 4.0.6 on 2022-10-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_option_json'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='ecommerce_product11111',
        ),
    ]
