# Generated by Django 4.0.7 on 2022-10-12 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0008_delete_usersellerarea'),
        ('product', '0009_alter_product_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(blank=True, related_name='my_review', through='product.ProductReview', to=settings.AUTH_USER_MODEL),
        ),
    ]
