# Generated by Django 4.0.6 on 2022-10-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='ecommerce_product',
        ),
    ]
