# Generated by Django 4.0.7 on 2022-10-12 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='content',
            new_name='review',
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
