# Generated by Django 4.0.6 on 2022-10-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='option_json',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
