# Generated by Django 4.0.7 on 2022-10-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productqna'),
    ]

    operations = [
        migrations.AddField(
            model_name='productqna',
            name='status',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
