# Generated by Django 4.0.6 on 2022-10-06 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_product_option_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'ecommerce_product_option_key',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productoptionkey')),
            ],
            options={
                'db_table': 'ecommerce_product_option_value',
                'managed': True,
            },
        ),
    ]
