# Generated by Django 4.1.3 on 2022-11-25 07:08

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0014_productvariant_deleted_at_productvariant_is_deleted_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReviewImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(upload_to=product.models.review_img_upload_to),
                ),
                (
                    "product_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productreview",
                    ),
                ),
            ],
            options={
                "db_table": "ecommerce_product_review_image",
            },
        ),
    ]
