# Generated by Django 4.0.6 on 2022-10-06 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productoptionkey_productoptionvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ecommerce_product_variant',
            },
        ),
        migrations.CreateModel(
            name='ProductVariantValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariant')),
            ],
            options={
                'db_table': 'ecommerce_product_variant_value',
            },
        ),
        migrations.RemoveField(
            model_name='productoptionvalue',
            name='key',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productthumbnail',
            options={},
        ),
        migrations.DeleteModel(
            name='ProductOptionKey',
        ),
        migrations.DeleteModel(
            name='ProductOptionValue',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
