# Generated by Django 4.0.7 on 2022-11-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_productqna_status_productqna_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_column='product_name', max_length=255),
        ),
    ]
