# Generated by Django 4.1.3 on 2022-11-08 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='uid',
            new_name='pg_uid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
