# Generated by Django 4.1.3 on 2022-11-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='answered_at',
            field=models.DateTimeField(null=True),
        ),
    ]
