# Generated by Django 4.0.7 on 2022-10-26 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QnA',
        ),
    ]
