# Generated by Django 4.1.3 on 2022-11-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RevenueAdmin',
        ),
        migrations.DeleteModel(
            name='RevenueSeller',
        ),
    ]
