# Generated by Django 4.1.3 on 2022-11-10 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_revenueseller_seller_alter_revenueadmin_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenueadmin',
            old_name='refunt_amount',
            new_name='refund_amount',
        ),
        migrations.RenameField(
            model_name='revenueseller',
            old_name='refunt_amount',
            new_name='refund_amount',
        ),
    ]
