# Generated by Django 4.1.3 on 2022-11-11 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revenue', '0002_delete_revenueadmin_delete_revenueseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('used_point_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'ecommerce_revenue_admin',
            },
        ),
        migrations.CreateModel(
            name='RevenueSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ecommerce_revenue_seller',
            },
        ),
    ]
