# Generated by Django 4.1.3 on 2023-07-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_categoryfirst_is_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryfirst",
            name="is_display",
            field=models.BooleanField(default=True),
        ),
    ]
