# Generated by Django 4.1.3 on 2022-12-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="schedule_date",
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
