# Generated by Django 4.0.7 on 2022-10-12 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_area_productarea'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant_value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.productvariantvalue'),
            preserve_default=False,
        ),
    ]
