# Generated by Django 4.0.7 on 2022-10-12 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_area_productarea'),
        ('cart', '0002_cartitem_variant_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variant_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productvariantvalue'),
        ),
    ]
