# Generated by Django 4.0.7 on 2022-10-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_variant_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='active',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='active',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
