# Generated by Django 4.0.6 on 2022-10-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='option',
        ),
    ]
