# Generated by Django 4.1.3 on 2022-11-15 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='is_refunded',
        ),
    ]
