# Generated by Django 4.1.3 on 2022-11-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0002_remove_payment_is_paid_remove_refund_is_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refund',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
