# Generated by Django 4.1.3 on 2022-12-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charge", "0003_payment_is_paid_refund_is_refunded"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
    ]
