# Generated by Django 4.1.3 on 2022-12-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charge", "0004_payment_paid_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
