# Generated by Django 4.1.3 on 2022-12-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charge", "0005_alter_payment_paid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="referrer",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="payment",
            table="charge_payment",
        ),
        migrations.AlterModelTable(
            name="refund",
            table="charge_refund",
        ),
    ]
