# Generated by Django 4.1.3 on 2022-12-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charge", "0008_alter_payment_referrer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="referrer",
            field=models.CharField(default="homecare", max_length=200),
        ),
    ]
