# Generated by Django 4.1.3 on 2022-12-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charge", "0010_rename_payment_uid_payment_refno_payment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="is_paid",
        ),
    ]
