# Generated by Django 4.1.3 on 2022-12-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charge", "0011_remove_payment_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="txnid",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
