# Generated by Django 4.1.3 on 2022-12-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charge", "0012_payment_txnid"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
