# Generated by Django 4.1.3 on 2022-12-26 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charge", "0013_payment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
