# Generated by Django 4.1.3 on 2022-12-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charge", "0014_alter_payment_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="created_at",
        ),
    ]
