# Generated by Django 4.1.3 on 2022-12-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charge", "0016_payment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
