# Generated by Django 4.1.3 on 2022-11-11 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
        ('charge', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('used_point', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charge.payment')),
                ('shpping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.usershippingaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ecommerce_order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_uid', models.CharField(max_length=255, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(null=True)),
                ('is_refund_requested', models.BooleanField(default=False)),
                ('refund_requested_at', models.DateTimeField(null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('variant', models.CharField(max_length=255, null=True)),
                ('variant_value', models.CharField(max_length=255, null=True)),
                ('variant_price', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('ordered_quantity', models.PositiveIntegerField()),
                ('shipped_quantity', models.PositiveIntegerField(default=0)),
                ('is_subscribe', models.BooleanField(default=False)),
                ('schedule_date', models.DateTimeField()),
                ('order_status', models.CharField(max_length=255)),
                ('status', models.CharField(default='결제대기', max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('refund', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charge.refund')),
            ],
            options={
                'db_table': 'ecommerce_order_item',
            },
        ),
    ]
