# Generated by Django 4.0.7 on 2022-10-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_uid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
