# Generated by Django 4.0.7 on 2022-10-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_productqna_status_productqna_deleted_at_and_more'),
        ('order', '0002_remove_order_item_order_order_item_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_item',
            field=models.ManyToManyField(related_name='order_orderitem_set', through='order.OrderItem', to='product.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant_value',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
