# Generated by Django 4.0.7 on 2022-10-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_order_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_uid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
