# Generated by Django 4.0.7 on 2022-10-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_total_price_orderitem_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='product_price',
        ),
    ]
