# Generated by Django 4.0.7 on 2022-10-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitem_order_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='visit_at',
            new_name='visited_at',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='schedule_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
