# Generated by Django 4.0.7 on 2022-10-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_price_orderitem_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
