# Generated by Django 4.0.7 on 2022-10-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_visit_at_orderitem_visited_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='schedule_date',
            field=models.DateTimeField(null=True),
        ),
    ]
