# Generated by Django 4.1.3 on 2022-11-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderitem_shipping_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
    ]
