# Generated by Django 4.0.7 on 2022-10-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderitem_product_name_alter_orderitem_variant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
