# Generated by Django 4.0.7 on 2022-10-26 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderitem_schedule_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='schedule_date',
        ),
    ]
