# Generated by Django 4.0.7 on 2022-10-26 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_orderitem_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='schedule_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
