# Generated by Django 4.1.3 on 2022-11-15 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0002_remove_payment_is_paid_remove_refund_is_refunded'),
        ('order', '0007_orderitem_order_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charge.payment'),
        ),
    ]
