# Generated by Django 4.0.7 on 2022-10-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderitem_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='schedule_date',
            field=models.DateTimeField(),
        ),
    ]
