# Generated by Django 4.0.7 on 2022-10-25 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_oder_uid_alter_order_pg_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oder_uid',
            new_name='order_uid',
        ),
    ]
