# Generated by Django 4.0.7 on 2022-10-26 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orderitem_schedule_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='visited_at',
            new_name='delivered_at',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='is_visited',
            new_name='is_delivered',
        ),
    ]
