# Generated by Django 4.1.3 on 2022-11-15 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0003_payment_is_paid_refund_is_refunded'),
        ('order', '0008_alter_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='charge.payment'),
            preserve_default=False,
        ),
    ]
