# Generated by Django 4.0.7 on 2022-10-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_order_cancelled_at_remove_order_is_cancelled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='ordered_quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipped_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
