# Generated by Django 4.1.3 on 2022-12-21 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("charge", "0010_rename_payment_uid_payment_refno_payment_user"),
        ("order", "0011_order_txnid_alter_orderitem_order_item_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="charge.payment",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="txnid",
            field=models.CharField(
                default=16366102621648392685, max_length=255, verbose_name="주문번호"
            ),
        ),
    ]
