# Generated by Django 4.0.7 on 2022-10-25 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_rename_quantity_orderitem_ordered_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
