# Generated by Django 4.0.7 on 2022-10-25 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0014_remove_productqna_status_productqna_deleted_at_and_more'),
        ('account', '0008_delete_usersellerarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0012_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_uid', models.CharField(max_length=255, null=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(null=True)),
                ('shpping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.usershippingaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ecommerce_order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(null=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('refunded_at', models.DateTimeField(null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.PositiveIntegerField()),
                ('variant', models.CharField(max_length=255, null=True)),
                ('variant_value', models.CharField(max_length=255, null=True)),
                ('variant_price', models.PositiveIntegerField(null=True)),
                ('ordered_quantity', models.PositiveIntegerField()),
                ('shipped_quantity', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'ecommerce_order_item',
            },
        ),
    ]
