# Generated by Django 4.0.7 on 2022-10-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_subscribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='visit_at',
            field=models.DateTimeField(null=True),
        ),
    ]
