# Generated by Django 4.1.3 on 2022-12-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0014_alter_order_txnid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="txnid",
            field=models.CharField(
                default=13204832303247921645, max_length=255, verbose_name="주문번호"
            ),
        ),
    ]
