# Generated by Django 4.0.7 on 2022-10-25 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_orderitem_is_subscribe_orderitem_is_visited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
