# Generated by Django 4.1.3 on 2023-06-27 06:33

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0022_alter_order_txnid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="txnid",
            field=models.CharField(
                default=order.models.hexdec_uniqid, max_length=255, verbose_name="주문번호"
            ),
        ),
    ]
